"""create initial persistence schema

Revision ID: 7a70c733813a
Revises: 
Create Date: 2026-09-02 16:49:35.813402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a70c733813a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('gsc_site_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('ai_citations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.Enum('CHATGPT', 'PERPLEXITY', 'GEMINI', 'COPILOT', 'AI_OVERVIEWS', name='aiengine'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('cited', sa.Boolean(), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('answer_excerpt', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_citations_checked_at'), 'ai_citations', ['checked_at'], unique=False)
    op.create_index('ix_ai_citations_project_engine_checked_at', 'ai_citations', ['project_id', 'engine', 'checked_at'], unique=False)
    op.create_index(op.f('ix_ai_citations_project_id'), 'ai_citations', ['project_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_project_id'), 'audits', ['project_id'], unique=False)
    op.create_index('ix_audits_project_url', 'audits', ['project_id', 'url'], unique=False)
    op.create_table('keyword_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('pillar_topic', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'label', name='uq_keyword_cluster_project_label')
    )
    op.create_index(op.f('ix_keyword_clusters_project_id'), 'keyword_clusters', ['project_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_project_id'), 'workflow_runs', ['project_id'], unique=False)
    op.create_index('ix_workflow_runs_project_started_at', 'workflow_runs', ['project_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_started_at'), 'workflow_runs', ['started_at'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('intent', sa.Enum('INFORMATIONAL', 'COMMERCIAL', 'TRANSACTIONAL', 'NAVIGATIONAL', name='searchintent'), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('opportunity', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'term', name='uq_keyword_project_term')
    )
    op.create_index(op.f('ix_keywords_cluster_id'), 'keywords', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('keyword_id', sa.String(length=32), nullable=True),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', name='contentstatus'), nullable=False),
    sa.Column('aeo_score', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_content_project_slug')
    )
    op.create_index(op.f('ix_contents_cluster_id'), 'contents', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_contents_keyword_id'), 'contents', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_contents_project_id'), 'contents', ['project_id'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('keyword_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_checked_at'), 'rankings', ['checked_at'], unique=False)
    op.create_index('ix_rankings_keyword_checked_at', 'rankings', ['keyword_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_rankings_keyword_id'), 'rankings', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_rankings_project_id'), 'rankings', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rankings_project_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_keyword_id'), table_name='rankings')
    op.drop_index('ix_rankings_keyword_checked_at', table_name='rankings')
    op.drop_index(op.f('ix_rankings_checked_at'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_contents_project_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_keyword_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_cluster_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_cluster_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_workflow_runs_started_at'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_project_started_at', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_project_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_keyword_clusters_project_id'), table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index('ix_audits_project_url', table_name='audits')
    op.drop_index(op.f('ix_audits_project_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_ai_citations_project_id'), table_name='ai_citations')
    op.drop_index('ix_ai_citations_project_engine_checked_at', table_name='ai_citations')
    op.drop_index(op.f('ix_ai_citations_checked_at'), table_name='ai_citations')
    op.drop_table('ai_citations')
    op.drop_table('projects')
    # ### end Alembic commands ###
